//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_DASHBOARD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cgsapqa2.plumrose.com:8009/sap/bc/srt/rfc/sap/zsd_dashboard_method01/020/z" +
            "sd_dashboard_method01/zsd_dashboard_method01")]
        public string B2B_DASHBOARD_ServiceSap_ZSD_DASHBOARD_METHOD01 {
            get {
                return ((string)(this["B2B_DASHBOARD_ServiceSap_ZSD_DASHBOARD_METHOD01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vecgupra19.plumrose.com/servicios/loaddb/service.php")]
        public string B2B_DASHBOARD_ws_b2b_loaddb_wsdm {
            get {
                return ((string)(this["B2B_DASHBOARD_ws_b2b_loaddb_wsdm"]));
            }
        }
    }
}
